Remove "files" from package.json as it conflicts with ".vscodeignore"
This resolves build issue:

    Error: Both a .vscodeignore file and a "files" property
    in package.json were found. VSCE does not support combining
    both strategies. Either remove the .vscodeignore file or the
    "files" property in package.json.

Fixes #125